# Generated by Django 5.2.4 on 2025-12-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('places', '0002_place_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='packages', to='places.place'),
        ),
    ]
