# Generated by Django 5.2.4 on 2025-12-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_theme_user_age_user_gender_user_nickname_and_more'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='places', to='accounts.theme'),
        ),
    ]
